"""enterprise_security_foundation

Revision ID: 0015
Revises: 0014
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0015'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=20), nullable=False),
    sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('step_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_type', sa.String(length=24), nullable=False),
    sa.Column('user_agent_summary', sa.String(length=100), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_index('ix_auth_sessions_user_expires', 'auth_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('mfa_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_challenges_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_challenges')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_mfa_challenges_token_hash'))
    )
    op.create_index('ix_mfa_challenges_user_expires', 'mfa_challenges', ['user_id', 'expires_at'], unique=False)
    op.create_table('mfa_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=512), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_step', sa.Integer(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_credentials_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_mfa_credentials'))
    )
    op.create_table('mfa_recovery_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_recovery_codes_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_recovery_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_mfa_recovery_codes_code_hash'))
    )
    op.create_index('ix_mfa_recovery_codes_user_unused', 'mfa_recovery_codes', ['user_id', 'used_at'], unique=False)
    op.create_table('organization_security_policies',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('require_sso', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('max_session_lifetime_minutes', sa.Integer(), server_default='1440', nullable=False),
    sa.Column('allowed_email_domains', sa.JSON(), nullable=False),
    sa.Column('require_manual_approval_above_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('block_critical_risk', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_approval_for_high_risk', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_session_lifetime_minutes BETWEEN 15 AND 1440', name=op.f('ck_organization_security_policies_max_session_lifetime_range')),
    sa.CheckConstraint('require_manual_approval_above_amount IS NULL OR require_manual_approval_above_amount > 0', name=op.f('ck_organization_security_policies_approval_threshold_positive')),
    sa.CheckConstraint('session_timeout_minutes BETWEEN 5 AND 60', name=op.f('ck_organization_security_policies_session_timeout_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_security_policies_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_organization_security_policies'))
    )
    op.create_table('sso_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('provider_type', sa.String(length=16), server_default='OIDC', nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_client_secret', sa.String(length=1024), nullable=False),
    sa.Column('discovery_url', sa.String(length=1024), nullable=False),
    sa.Column('allowed_domains', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sso_connections_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sso_connections'))
    )
    op.create_index('ix_sso_connections_org_status', 'sso_connections', ['organization_id', 'status'], unique=False)
    op.create_table('sso_login_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sso_login_tickets_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sso_login_tickets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sso_login_tickets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sso_login_tickets_token_hash'))
    )
    op.create_table('sso_login_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_code_verifier', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['sso_connections.id'], name=op.f('fk_sso_login_attempts_connection_id_sso_connections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sso_login_attempts')),
    sa.UniqueConstraint('state_hash', name=op.f('uq_sso_login_attempts_state_hash'))
    )
    op.add_column('security_events', sa.Column('severity', sa.String(length=12), server_default='info', nullable=False))
    op.add_column('security_events', sa.Column('details', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    op.alter_column('security_events', 'actor_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_events', 'actor_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('security_events', 'details')
    op.drop_column('security_events', 'severity')
    op.drop_table('sso_login_attempts')
    op.drop_table('sso_login_tickets')
    op.drop_index('ix_sso_connections_org_status', table_name='sso_connections')
    op.drop_table('sso_connections')
    op.drop_table('organization_security_policies')
    op.drop_index('ix_mfa_recovery_codes_user_unused', table_name='mfa_recovery_codes')
    op.drop_table('mfa_recovery_codes')
    op.drop_table('mfa_credentials')
    op.drop_index('ix_mfa_challenges_user_expires', table_name='mfa_challenges')
    op.drop_table('mfa_challenges')
    op.drop_index('ix_auth_sessions_user_expires', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
